

// --------------- PROJECT  -  1 App.Vwo  -----------  // 

url = https://app.vwo.com
dashboardURL = https://app.vwo.com/#/dashboard/
username=20010041034@gateway.edu.in
password=Paliwal@2609
expected_username = Edu

invalid_username = abc@gmail.com
invalid_password = 1234


error_msg = Your email, password, IP address or location did not match
browser=Chrome

trailPage_err = An account with this email already exists. Login Here



// --------------- PROJECT  -2 OrangeHRM  -----------  // 


ohr_username = admin
ohr_password = Hacker@4321
ohr_expected_username = PIM
ohr_url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login




